// Supported stores
export const PRIORITY_STORES = [
  { name: 'Aldi', slug: 'aldi', website: 'https://www.aldi.us' },
  { name: 'Lidl', slug: 'lidl', website: 'https://www.lidl.com' },
  { name: 'Harris Teeter', slug: 'harris-teeter', website: 'https://www.harristeeter.com' },
  { name: 'Safeway', slug: 'safeway', website: 'https://www.safeway.com' },
  { name: 'Walmart', slug: 'walmart', website: 'https://www.walmart.com' },
  { name: 'Kroger', slug: 'kroger', website: 'https://www.kroger.com' },
  { name: 'Publix', slug: 'publix', website: 'https://www.publix.com' },
  { name: 'Target', slug: 'target', website: 'https://www.target.com' },
  { name: 'Costco', slug: 'costco', website: 'https://www.costco.com' },
  { name: "Sam's Club", slug: 'sams-club', website: 'https://www.samsclub.com' },
  { name: "Trader Joe's", slug: 'trader-joes', website: 'https://www.traderjoes.com' },
  { name: 'Whole Foods', slug: 'whole-foods', website: 'https://www.wholefoodsmarket.com' },
  { name: 'Food Lion', slug: 'food-lion', website: 'https://www.foodlion.com' },
  { name: 'Giant', slug: 'giant', website: 'https://giantfood.com' },
  { name: 'Stop & Shop', slug: 'stop-and-shop', website: 'https://stopandshop.com' },
  { name: 'ShopRite', slug: 'shoprite', website: 'https://www.shoprite.com' },
  { name: 'Meijer', slug: 'meijer', website: 'https://www.meijer.com' },
  { name: 'H-E-B', slug: 'heb', website: 'https://www.heb.com' },
  { name: 'Wegmans', slug: 'wegmans', website: 'https://www.wegmans.com' },
  { name: 'Albertsons', slug: 'albertsons', website: 'https://www.albertsons.com' },
  { name: 'Vons', slug: 'vons', website: 'https://www.vons.com' },
  { name: "Ralph's", slug: 'ralphs', website: 'https://www.ralphs.com' },
  { name: 'Food 4 Less', slug: 'food-4-less', website: 'https://www.food4less.com' },
  { name: 'WinCo', slug: 'winco', website: 'https://www.wincofoods.com' },
  { name: 'Sprouts', slug: 'sprouts', website: 'https://www.sprouts.com' },
  { name: 'Fresh Market', slug: 'fresh-market', website: 'https://www.thefreshmarket.com' },
  { name: 'ACME', slug: 'acme', website: 'https://www.acmemarkets.com' },
  { name: 'Winn-Dixie', slug: 'winn-dixie', website: 'https://www.winndixie.com' },
  { name: 'Piggly Wiggly', slug: 'piggly-wiggly', website: 'https://www.pigglywiggly.com' },
  { name: 'Dollar General', slug: 'dollar-general', website: 'https://www.dollargeneral.com' },
  { name: 'CVS', slug: 'cvs', website: 'https://www.cvs.com' },
  { name: 'Walgreens', slug: 'walgreens', website: 'https://www.walgreens.com' },
  { name: 'Rite Aid', slug: 'rite-aid', website: 'https://www.riteaid.com' },
  { name: 'BI-LO', slug: 'bi-lo', website: 'https://www.bi-lo.com' },
  { name: 'Food City', slug: 'food-city', website: 'https://www.foodcity.com' },
  { name: 'Ingles', slug: 'ingles', website: 'https://www.ingles-markets.com' },
  { name: "Harvey's", slug: 'harveys', website: 'https://www.harveys.com' },
  { name: "Fry's", slug: 'frys', website: 'https://www.frysfood.com' },
  { name: "Smith's", slug: 'smiths', website: 'https://www.smithsfoodanddrug.com' },
  { name: 'King Soopers', slug: 'king-soopers', website: 'https://www.kingsoopers.com' },
  { name: 'City Market', slug: 'city-market', website: 'https://www.citymarket.com' },
  { name: "Mariano's", slug: 'marianos', website: 'https://www.marianos.com' },
  { name: 'Jewel-Osco', slug: 'jewel-osco', website: 'https://www.jewelosco.com' },
  { name: 'Tom Thumb', slug: 'tom-thumb', website: 'https://www.tomthumb.com' },
  { name: "Randall's", slug: 'randalls', website: 'https://www.randalls.com' },
] as const

// Deal categories
export const CATEGORIES = [
  { label: 'All', value: '' },
  { label: 'Produce', value: 'produce' },
  { label: 'Meat', value: 'meat' },
  { label: 'Dairy', value: 'dairy' },
  { label: 'Pantry', value: 'pantry' },
  { label: 'Frozen', value: 'frozen' },
  { label: 'Bakery', value: 'bakery' },
  { label: 'Beverages', value: 'beverages' },
  { label: 'Snacks', value: 'snacks' },
  { label: 'Household', value: 'household' },
  { label: 'Other', value: 'other' },
] as const

export type Category = (typeof CATEGORIES)[number]['value']

// Local storage keys
export const STORAGE_KEYS = {
  ZIP_CODE: 'gg_zip_code',
  SELECTED_STORES: 'gg_selected_stores',
  WATCH_LIST: 'gg_watch_list',
  ONBOARDING_COMPLETE: 'gg_onboarding_complete',
} as const
